Repository AAEmu/AAEmu, pull requests merged in 2022-11, with the labels that each got.

#535 Add ItemConversion so Evenstones work
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/GameData/ItemConversionGameData.cs
  AAEmu.Game/Models/ClientData/Hmap.cs
  AAEmu.Game/Models/Game/Items/ItemConversionData.cs
  AAEmu.Game/Models/Game/Items/Templates/ItemTemplate.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ApplyReagents.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ItemConversion.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ItemSocketing.cs
  AAEmu.Game/Models/StaticValues/ItemImplEnum.cs
Labels: missing functionality

#537 [Game] WIP: Quest bug fixes:
  AAEmu.Game/Core/Managers/SkillManager.cs
  AAEmu.Game/Models/Game/Skills/Buff.cs
  AAEmu.Game/Models/Game/Skills/Effects/AccountAttributeEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/CinemalEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/NpcControlEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpawnFishEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/TrainCraftRankEffect.cs
Labels: bug, Quest

#542 [Game] Fix: Recover item from doodad
  AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs
Labels: bug
