Repository AAEmu/AAEmu, pull requests merged in 2022-07, with the labels that each got.

#472 [All] Fix: MySqlDatabseUpdater warning
  AAEmu.Commons/Utils/Updater/MySqlDatabaseUpdater.cs
Labels: bug

#475 [All] Consolidated MySQL.cs into Commons
  AAEmu.Commons/Models/MySqlConnectionSettings.cs
  AAEmu.Commons/Utils/DB/MySQL.cs
  AAEmu.Game/Core/Managers/AuctionManager.cs
  AAEmu.Game/Core/Managers/CashShopManager.cs
  AAEmu.Game/Core/Managers/ExpeditionManager.cs
  AAEmu.Game/Core/Managers/FamilyManager.cs
  AAEmu.Game/Core/Managers/FriendMananger.cs
  AAEmu.Game/Core/Managers/HousingManager.cs
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Core/Managers/MailManager.cs
  AAEmu.Game/Core/Managers/MusicManager.cs
  AAEmu.Game/Core/Managers/NameManager.cs
  AAEmu.Game/Core/Managers/SaveManager.cs
  AAEmu.Game/Core/Managers/Stream/UccManager.cs
  AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
  AAEmu.Game/Core/Managers/World/SpawnManager.cs
  AAEmu.Game/Core/Network/Connections/GameConnection.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/AppConfiguration.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Char/CharacterBlocked.cs
  AAEmu.Game/Models/Game/Char/CharacterQuests.cs
  AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
  AAEmu.Game/Program.cs
  AAEmu.Game/Utils/DB/MySQL.cs
  AAEmu.Game/Utils/IdManager.cs
  AAEmu.Login/Core/Controllers/GameController.cs
  AAEmu.Login/Core/Controllers/LoginController.cs
  AAEmu.Login/LoginService.cs
  AAEmu.Login/Models/AppConfiguration.cs
  AAEmu.Login/Program.cs
  AAEmu.Login/Utils/IdManager.cs
  AAEmu.Login/Utils/MySQL.cs
Labels: enhancement

#476 [All] Update: MySqlDatabaseUpdate can now be skipped
  AAEmu.Commons/Utils/Updater/MySqlDatabaseUpdater.cs
Labels: enhancement

#451 /damage GM command is now based on health percentage
  AAEmu.Game/Scripts/Commands/Damage.cs
Labels: good first issue

#479 [Game] Updated damage command
  AAEmu.Game/Program.cs
  AAEmu.Game/Scripts/Commands/Damage.cs
  AAEmu.Login/Program.cs
Labels: enhancement, missing functionality

#480 [Game] AccessLevelManager
  AAEmu.Game/Core/Managers/AccessLevelManager.cs
  AAEmu.Game/Core/Managers/CommandManager.cs
  AAEmu.Game/Models/Game/AccessLevel.cs
Labels: enhancement

#483 [Game] Fix: Help
  AAEmu.Game/Scripts/Commands/Help.cs
Labels: bug

#486 [Game] Items with expiration date and limited buff effect times
  AAEmu.Game/AAEmu.Game.csproj
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Core/Packets/G2C/SCSyncItemLifespanPacket.cs
  AAEmu.Game/Models/Game/Char/CharacterEquipment.cs
  AAEmu.Game/Models/Game/Char/Inventory.cs
  AAEmu.Game/Models/Game/Items/Containers/CofferContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/EquipmentContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
  AAEmu.Game/Models/Game/Items/EquipItem.cs
  AAEmu.Game/Models/Game/Items/Item.cs
  AAEmu.Game/Models/Game/Items/Templates/EquipItemTemplate.cs
  AAEmu.Game/Models/Game/Items/Templates/ItemTemplate.cs
  AAEmu.Game/Models/Tasks/Item/ItemTimerTask.cs
  AAEmu.Game/Program.cs
  AAEmu.Game/Scripts/Commands/ExpireItem.cs
  SQL/updates/2022-07-28_aaemu_game_expire_item.sql
Labels: missing functionality
