Repository AAEmu/AAEmu, pull requests merged in 2023-10, with the labels that each got.

#738 [Game] Fix faction check and AoE related hits
  AAEmu.Game/Models/Game/Faction/SystemFaction.cs
  AAEmu.Game/Models/Game/Skills/Effects/BuffEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
  AAEmu.Game/Models/Game/Units/BaseUnit.cs
Labels: bug

#741 [Game] Fix housing related issue
  AAEmu.Game/Core/Managers/HousingManager.cs
  AAEmu.Game/Core/Packets/C2G/CSDecorateHousePacket.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncUse.cs
  AAEmu.Game/Scripts/Commands/TestHouse.cs
Labels: bug

#742 [Game] Hotfix House TlId
  AAEmu.Game/Core/Managers/HousingManager.cs
Labels: bug

#743 [Game] CanAttack added null-check
  AAEmu.Game/Models/Game/Units/BaseUnit.cs
Labels: bug

#745 [Game] Reset aggro on safe zones
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/ReturnStateBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Framework/NpcAi.cs
  AAEmu.Game/Models/Game/NPChar/Npc.cs
  AAEmu.Game/Models/Game/Skills/BuffConstants.cs
  AAEmu.Game/Models/Game/Units/BaseUnit.cs
  AAEmu.Game/Models/Game/Units/Buffs.cs
  AAEmu.Game/Models/StaticValues/TagsEnum.cs
Labels: bug

#748 [Game] Fix: Mob Hostility check
  AAEmu.Game/Models/Game/Units/BaseUnit.cs
Labels: bug

#755 [Game] Fix - SkillTlId limit
  AAEmu.Game/Core/Managers/ISkillManager.cs
  AAEmu.Game/Core/Managers/Id/SkillTlIdManager.cs
  AAEmu.Game/Core/Managers/SkillManager.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTree.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
  AAEmu.IntegrationTests/Models/Game/Quests/QuestTests.cs
Labels: bug, enhancement

#756 [Game] Fix crafts without WI
  AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs
Labels: bug

#761 [Game] Fix Quests starting items and gather objective
  AAEmu.Game/Core/Managers/QuestManager.cs
  AAEmu.Game/Models/Game/Char/CharacterQuests.cs
  AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGather.cs
  AAEmu.Game/Models/Game/Quests/Quest.cs
  AAEmu.Game/Models/Game/Skills/Effects/AcceptQuestEffect.cs
Labels: bug, Quest

#764 Update to Wiki & Docs
  AAEmu.Game/Utils/IdManager.cs
  AAEmu.Login/Utils/IdManager.cs
  AAEmu.sln
  Docs/components.md
  Docs/getstarted.md
Labels: documentation, review required

#765 [Game] Tradepack and Slave related update
  AAEmu.Game/Core/Managers/HousingManager.cs
  AAEmu.Game/Core/Managers/Id/CharacterIdManager.cs
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Core/Managers/MateManager.cs
  AAEmu.Game/Core/Managers/SaveManager.cs
  AAEmu.Game/Core/Managers/SlaveManager.cs
  AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
  AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
  AAEmu.Game/Core/Managers/World/EnterWorldManager.cs
  AAEmu.Game/Core/Managers/World/SpawnManager.cs
  AAEmu.Game/Core/Managers/World/WorldManager.cs
  AAEmu.Game/Core/Packets/C2G/CSChangeTargetPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSDestroySlavePacket.cs
  AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSStopCastingPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCUnitStatePacket.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Char/Inventory.cs
  AAEmu.Game/Models/Game/DoodadObj/Details/DoodadFuncConsumeChangerItem.cs
  AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncAttachment.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncConsumeChanger.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncConsumeChangerItem.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncUse.cs
  AAEmu.Game/Models/Game/Items/BigFish.cs
  AAEmu.Game/Models/Game/Items/Containers/CofferContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/EquipmentContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
  AAEmu.Game/Models/Game/Items/EquipItem.cs
  AAEmu.Game/Models/Game/Items/Item.cs
  AAEmu.Game/Models/Game/Items/MusicSheetItem.cs
  AAEmu.Game/Models/Game/Items/Summon.cs
  AAEmu.Game/Models/Game/Items/SummonMate.cs
  AAEmu.Game/Models/Game/Items/SummonSlave.cs
  AAEmu.Game/Models/Game/Items/Templates/SummonMateTemplate.cs
  AAEmu.Game/Models/Game/Items/Templates/SummonSlaveTemplate.cs
  AAEmu.Game/Models/Game/Items/UccItem.cs
  AAEmu.Game/Models/Game/NPChar/Npc.cs
  AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs
  AAEmu.Game/Models/Game/Skills/Effects/PutDownBackpackEffect.cs
  AAEmu.Game/Models/Game/Slaves/SlaveDropDoodad.cs
  AAEmu.Game/Models/Game/Slaves/SlaveModelAttachPoint.cs
  AAEmu.Game/Models/Game/Slaves/SlaveSpawner.cs
  AAEmu.Game/Models/Game/Slaves/SlaveTemplate.cs
  AAEmu.Game/Models/Game/Units/Slave.cs
  AAEmu.Game/Models/Game/Units/Unit.cs
  AAEmu.Game/Models/Game/World/Transform/Transform.cs
  AAEmu.Game/Scripts/Commands/GetAttribute.cs
  AAEmu.Game/Scripts/SubCommands/Slaves/SlaveRemoveSubCommand.cs
  AAEmu.Game/Scripts/SubCommands/Slaves/SlaveSpawnSubCommand.cs
  AAEmu.UnitTests/Game/Models/Game/Items/Containers/InventoryTests.cs
  AAEmu.sln
  SQL/aaemu_game.sql
  SQL/updates/2023-10-08_aaemu_game_slaves.sql
Labels: bug, enhancement, missing functionality

#766 [Game] SkillTlId fixing?
  AAEmu.Game/Core/Managers/Id/SkillTlIdManager.cs
  AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSStopCastingPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCSkillEndedPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCSkillStartedPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCSkillStopped.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/Game/AI/v2/Framework/Behavior.cs
  AAEmu.Game/Models/Game/Quests/Quest.cs
  AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTree.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
  AAEmu.Game/Models/Game/Units/Combat.cs
  AAEmu.IntegrationTests/Models/Game/Quests/QuestTests.cs
Labels: bug

#767 [Game] Various small fixes
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Char/CharacterActability.cs
  AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFinal.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
Labels: bug

#769 [Game] Tradepacks and slaves update part 2
  AAEmu.Game/Core/Managers/DuelManager.cs
  AAEmu.Game/Core/Managers/FishSchoolManager.cs
  AAEmu.Game/Core/Managers/MateManager.cs
  AAEmu.Game/Core/Managers/ModelManager.cs
  AAEmu.Game/Core/Managers/SlaveManager.cs
  AAEmu.Game/Core/Managers/World/WorldManager.cs
  AAEmu.Game/Core/Packets/C2G/CSChangeTargetPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
  AAEmu.Game/Data/slave_attach_points.json
  AAEmu.Game/Models/Game/AI/States/AAttackState.cs
  AAEmu.Game/Models/Game/AI/States/AlmightyAttackState.cs
  AAEmu.Game/Models/Game/AI/States/MoveToTargetState.cs
  AAEmu.Game/Models/Game/AI/States/ReturnToIdleState.cs
  AAEmu.Game/Models/Game/AI/States/RoamingState.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Archer/ArcherAttackBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/BigMonster/BigMonsterAttackBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AlmightyAttackBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AttackBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/DoNothingBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/IdleBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/ReturnStateBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/RoamingBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/SpawningBehavior.cs
  AAEmu.Game/Models/Game/AI/v2/Behaviors/WildBoar/WildBoatAttackBehavior.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Items/SummonSlave.cs
  AAEmu.Game/Models/Game/Models/ActorModel.cs
  AAEmu.Game/Models/Game/Models/GameStance.cs
  AAEmu.Game/Models/Game/Models/GameStanceType.cs
  AAEmu.Game/Models/Game/NPChar/Npc.cs
  AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/RepairSlaveEffect.cs
  AAEmu.Game/Models/Game/Skills/Templates/BuffTemplate.cs
  AAEmu.Game/Models/Game/Slaves/SlaveMountSkills.cs
  AAEmu.Game/Models/Game/Units/Buffs.cs
  AAEmu.Game/Models/Game/Units/Combat.cs
  AAEmu.Game/Models/Game/Units/Mate.cs
  AAEmu.Game/Models/Game/Units/Route/Track.cs
  AAEmu.Game/Models/Game/Units/Slave.cs
  AAEmu.Game/Models/Game/Units/Unit.cs
  AAEmu.Game/Models/Game/World/GameObject.cs
  AAEmu.Game/Models/Game/World/Interactions/Use.cs
  AAEmu.Game/Scripts/Commands/Kill.cs
  AAEmu.Game/Scripts/Commands/TestCombat.cs
Labels: bug, missing functionality

#772 [Game] Fix issue with empty skill reagents
  AAEmu.Game/Models/Game/Skills/Skill.cs
Labels: bug, missing functionality
