Repository AAEmu/AAEmu, pull requests merged in 2024-01, with the labels that each got.

#791 [Game] WIP: Work with dungeons:
  AAEmu.Game/Core/Managers/IndunManager.cs
  AAEmu.Game/Core/Managers/World/SpawnManager.cs
  AAEmu.Game/Core/Managers/World/WorldManager.cs
  AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
  AAEmu.Game/Data/Portal/worldgates.json
  AAEmu.Game/Data/Worlds/instance_howling_abyss/npc_spawns.json
  AAEmu.Game/Data/Worlds/instance_library/doodad_spawns.json
  AAEmu.Game/Data/Worlds/world_spawns.json
  AAEmu.Game/Models/Game/DoodadObj/DoodadSpawner.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncEnterInstance.cs
  AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncEnterSysInstance.cs
  AAEmu.Game/Models/Game/Indun/Dungeon.cs
  AAEmu.Game/Models/Game/NPChar/NpcSpawner.cs
  AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ExitArchemall.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/Return.cs
  AAEmu.Game/Models/Game/Units/UnitCooldowns.cs
Labels: In progress

#794 [Game] Fix - Quest status not properly loading
  AAEmu.Game/Models/Game/Char/CharacterQuests.cs
Labels: bug, quest

#796 [Game] Fix NPC respawn issues
  AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs
Labels: bug

#804 [Game] Fixed missing allow furniture recovery flag
  AAEmu.Game/Models/Game/Housing/House.cs
Labels: bug
