Repository AAEmu/AAEmu, pull requests merged in 2024-06, with the labels that each got.

#966 [Login] Added option to skip the host resolving
  AAEmu.Login/Core/Controllers/GameController.cs
  AAEmu.Login/ExampleConfig.json
  AAEmu.Login/Models/AppConfiguration.cs
Labels: enhancement

#967 [Game] Added ItemSet for SkillEffects
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Models/Game/Items/Templates/ItemSet.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
Labels: missing functionality

#981 [Game] Fixed issues with zone without sub-zones
  AAEmu.Game/Core/Managers/SubZoneManager.cs
Labels: bug

#983 feat: automatic docker installation
  .env.example
  .gitignore
  AAEmu.Game/Dockerfile
  AAEmu.Login/Dockerfile
  Docs/Docker-Installation-Guide.md
  Docs/docker-help.txt
  Scripts/clear-caches.sh
  Scripts/docker-install-local.ps1
  Scripts/docker-install-local.sh
  Scripts/docker-update-local.ps1
  Scripts/docker-update-local.sh
  Scripts/start.sh
  Scripts/stop-reset-db.sh
  Scripts/stop.sh
  docker-compose.yaml
Labels: enhancement, docker, documentation
