Repository AAEmu/AAEmu, pull requests merged in 2024-05, with the labels that each got.

#907 [Game] Add support for dyeing of gear
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Models/Game/Items/EquipItem.cs
  AAEmu.Game/Models/Game/Items/Templates/EquipItemTemplate.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/Dyeing.cs
Labels: missing functionality

#911 [Game] Fix Test Timbre Coupe spawn
  AAEmu.Game/Core/Managers/SlaveManager.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpawnEffect.cs
Labels: bug

#917 [Game] Fixed persistent Vehicle saving
  AAEmu.Game/Core/Managers/SlaveManager.cs
  AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
  AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
  AAEmu.Game/Core/Managers/World/SpawnManager.cs
  AAEmu.Game/Core/Packets/C2G/CSDespawnSlavePacket.cs
  AAEmu.Game/Core/Packets/C2G/CSDestroyItemPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSDestroySlavePacket.cs
  AAEmu.Game/Models/Game/Char/Inventory.cs
  AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
  AAEmu.Game/Models/Game/Items/Item.cs
  AAEmu.Game/Models/Game/Items/SummonMate.cs
  AAEmu.Game/Models/Game/Items/SummonSlave.cs
  AAEmu.Game/Models/Game/Units/BaseUnitType.cs
  AAEmu.Game/Models/Game/Units/Slave.cs
  SQL/aaemu_game.sql
  SQL/updates/2024-05-04_aaemu_game_slaves_update.sql
Labels: bug

#923 [Game] Accounts Rewrite
  AAEmu.Commons/Utils/StringExtensions.cs
  AAEmu.Game/AAEmu.Game.csproj
  AAEmu.Game/Configurations/CharacterDeleteSettings.json
  AAEmu.Game/Configurations/CharacterSettings.json
  AAEmu.Game/Configurations/World.json
  AAEmu.Game/Core/Managers/AccountManager.cs
  AAEmu.Game/Core/Managers/CashShopManager.cs
  AAEmu.Game/Core/Managers/CommandManager.cs
  AAEmu.Game/Core/Managers/LaborPowerManager.cs
  AAEmu.Game/Core/Managers/MateManager.cs
  AAEmu.Game/Core/Managers/NameManager.cs
  AAEmu.Game/Core/Managers/RadarManager.cs
  AAEmu.Game/Core/Managers/TimedRewardsManager.cs
  AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
  AAEmu.Game/Core/Network/Connections/GameConnection.cs
  AAEmu.Game/Core/Network/Game/GameNetwork.cs
  AAEmu.Game/Core/Packets/C2G/CSCreateCharacterPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSICSMoneyRequestPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSOffsets.cs
  AAEmu.Game/Core/Packets/C2G/CSPremiumServiceListPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSPremiumServiceMsgPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCCharacterCreationFailedPacket.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/Account/AccountDetails.cs
  AAEmu.Game/Models/AccountPayment.cs
  AAEmu.Game/Models/AppConfiguration.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Configurations.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/GiveBmMileage.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/GiveCashPoint.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ReceiveLuluLeaflet.cs
  AAEmu.Game/Models/StaticValues/CharacterCreateError.cs
  AAEmu.Game/Models/Tasks/CashShop/CashShopBuyTask.cs
  AAEmu.Game/Models/Tasks/LaborPower/LaborPowerTickStartTask.cs
  AAEmu.Game/Models/Tasks/Quests/QuestDailyResetTask.cs
  AAEmu.Game/Models/Tasks/TimedRewards/TimedRewardsTask.cs
  AAEmu.Game/Scripts/Commands/Help.cs
  AAEmu.UnitTests/Commons/Utils/StringExtensionsTest.cs
  AAEmu.sln
  Docs/docker-help.txt
  SQL/aaemu_game.sql
  SQL/updates/2024-05-10_aaemu_game_account_update.sql
Labels: bug, enhancement, review required

#926 [SQL] Make sure this is in UTC times
  SQL/aaemu_game.sql
  SQL/updates/2024-05-10_aaemu_game_account_update.sql
Labels: bug

#924 [Game] Tagging added for kill credit, XP, and Loot (with Rotate Winner and Free For All)
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Core/Managers/TeamManager.cs
  AAEmu.Game/Models/Game/NPChar/Npc.cs
  AAEmu.Game/Models/Game/NPChar/Tagging.cs
  AAEmu.Game/Models/Game/Team/TeamMember.cs
  AAEmu.Game/Models/Game/Units/Unit.cs
Labels: enhancement, good first issue

#951 [Game] Modernize IdManager
  AAEmu.Game/Utils/IdManager.cs
Labels: enhancement

#952 [Game] Added DefaultLanguage setting
  AAEmu.Game/Core/Managers/LocalizationManager.cs
  AAEmu.Game/ExampleConfig.json
  AAEmu.Game/Models/AppConfiguration.cs
Labels: enhancement

#953 [Game] Fixed Skill Points required
  AAEmu.Game/Core/Managers/ExperienceManager.cs
  AAEmu.Game/Core/Managers/SkillManager.cs
  AAEmu.Game/Models/Game/Char/CharacterSkills.cs
  AAEmu.Game/Models/Game/Skills/Templates/PassiveBuffTemplate.cs
  AAEmu.Game/Models/Game/Skills/Templates/SkillTemplate.cs
Labels: bug

#956 [Game] Added TargetNpcTagId check for effects
  AAEmu.Game/Models/Game/Skills/Effects/BuffEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
  AAEmu.Game/Models/Game/Skills/Skill.cs
  AAEmu.Game/Models/Game/Units/Unit.cs
Labels: bug, missing functionality, skill
