Repository AAEmu/AAEmu, pull requests merged in 2024-08, with the labels that each got.

#1060 [Game] Added support for taming nets
  AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
  AAEmu.Game/Core/Packets/G2C/SCAiAggroPacket.cs
  AAEmu.Game/Models/Game/NPChar/Npc.cs
  AAEmu.Game/Models/Game/NPChar/NpcTemplate.cs
  AAEmu.Game/Models/Game/Skills/Effects/AggroEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ApplyReagents.cs
  AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/CapturePet.cs
Labels: enhancement, missing functionality

#1061 [Game] Added online time tracking
  AAEmu.Game/Core/Managers/AccountManager.cs
  AAEmu.Game/Core/Managers/TimedRewardsManager.cs
  AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Tasks/Characters/CharacterOnlineTrackingTask.cs
  SQL/aaemu_game.sql
  SQL/updates/2024-08-04_aaemu_game_online_time.sql
Labels: enhancement, missing functionality

#1059 Parallelizing server initialization
  AAEmu.Game/Configurations/ClientData.json
  AAEmu.Game/Core/Managers/FamilyManager.cs
  AAEmu.Game/Core/Managers/FishSchoolManager.cs
  AAEmu.Game/Core/Managers/FriendManager.cs
  AAEmu.Game/Core/Managers/PublicFarmManager.cs
  AAEmu.Game/Core/Managers/World/SpawnManager.cs
  AAEmu.Game/Core/Network/Login/LoginProtocolHandler.cs
  AAEmu.Game/GameService.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Char/CharacterFriends.cs
  AAEmu.Login/AAEmu.Login.csproj
Labels: enhancement

#1077 [Game] Additional checks for trades
  AAEmu.Game/Core/Managers/TradeManager.cs
Labels: enhancement

#1079 [Game] Update to equipment change packet code and pet gear bonusses
  AAEmu.Game/Core/Managers/HousingManager.cs
  AAEmu.Game/Core/Managers/ItemManager.cs
  AAEmu.Game/Core/Managers/SlaveManager.cs
  AAEmu.Game/Core/Packets/C2G/CSChangeMateEquipmentPacket.cs
  AAEmu.Game/Core/Packets/C2G/CSSwapItemsPacket.cs
  AAEmu.Game/Core/Packets/G2C/SCMateEquipmentChangedPacket.cs
  AAEmu.Game/Models/Game/Char/Character.cs
  AAEmu.Game/Models/Game/Char/CharacterEquipment.cs
  AAEmu.Game/Models/Game/Char/CharacterMates.cs
  AAEmu.Game/Models/Game/Char/ICharacter.cs
  AAEmu.Game/Models/Game/Char/Inventory.cs
  AAEmu.Game/Models/Game/Items/Actions/ItemRemove.cs
  AAEmu.Game/Models/Game/Items/Containers/CofferContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/EquipmentContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
  AAEmu.Game/Models/Game/Items/Containers/MateEquipmentContainer.cs
  AAEmu.Game/Models/Game/Items/ItemAndLocation.cs
  AAEmu.Game/Models/Game/Items/ItemIdAndLocation.cs
  AAEmu.Game/Models/Game/Items/ItemLocation.cs
  AAEmu.Game/Models/Game/Units/IUnit.cs
  AAEmu.Game/Models/Game/Units/Mate.cs
  AAEmu.Game/Models/Game/Units/Unit.cs
  AAEmu.Game/Scripts/Commands/ShowInventory.cs
  AAEmu.UnitTests/Game/Models/Game/Items/Containers/InventoryTests.cs
Labels: bug, enhancement

#1089 [Game] Added code to validate Family member status on login
  AAEmu.Game/Core/Managers/FamilyManager.cs
  AAEmu.Game/Models/Game/Family.cs
Labels: bug
